name: CMake Build

on:
  push:
    branches: [ main ]
    paths:
      - '**.cpp'
      - '**.hpp'
      - 'CMakeLists.txt'
  pull_request:
    branches: [ main ]
    paths:
      - '**.cpp'
      - '**.hpp'
      - 'CMakeLists.txt'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    container: lagavulin16/vsomeip:dev

    steps:
    - uses: actions/checkout@v4
      name: Checkout repository

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build/

    - uses: actions/upload-artifact@v4
      with:
        name: build_artifact
        path: ./build